### ISSUE TITLE
vehicle-adapter freezes when generating CAM message

### ISSUE THREAD

**Issue by olesalscheider** [alexvoronov/geonetworking#11]
When I send an UDP packet containing information for a CAM message to the vehicle-adapter, the corresponding thread of the vehicle-adapter freezes.
It seems that it is stuck at line 304 of vehicle-adapter/src/main/java/net/gcdc/vehicle/
VehicleAdapter.java:

```
            new LowFrequencyContainer(
                                      new BasicVehicleContainerLowFrequency(
                                                                            VehicleRole.fromCode(vehicleRole),
                                                                            ExteriorLights.builder()
                                                                            .set(false, 
false, false, false, false, false, false, false)
                                                                            .create(),
                                                                            new 
PathHistory()
                                                                            ))
            :
            null;
```
Do you have an idea what could cause this?

**Comment by Zeverin** [comment]
Never seen that problem. Could you please try running the latest code from my fork and tell me if the issue persists?

**Comment by Heuvendw** [comment]
I can't reproduce it (using an older version of the stack) and a quick code inspection didn't reveal anything either.

**Comment by olesalscheider** [comment]
@Zeverin : The checks in your branch helped a lot - I messed up the endianess of the integers (the native format of our machine is LE). After fixing this, both your and the original version work. Thanks again.

**Comment by Zeverin** [comment]
Great. Glad you got it working.
