### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by victordolk** [alexvoronov/geonetworking#12]
When I execute the mvn clean install, an error appears due to the following

Running net.gcdc.geonetworking.BasicSocketTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.238 sec <<< FAILURE!
Running net.gcdc.geonetworking.DestinationTest

Tests in error:
  test(net.gcdc.geonetworking.BasicSocketTest): test timed out after 3000 milliseconds

Could you explain what the problem is here?

we use the udp2eth from Jan de Jongh

**Comment by alexvoronov** [comment]
Hi Victor! I never had errors in BasicSocketTest before. Could you please post the complete error log?

**Comment by jandejongh** [comment]
Hi Alex,

I hope I'm not hijacking an issue here, but I also found the tests to fail quite often, especially when trying to build on the Alix APU1D for I-GAME. In my case, the **BeaconTest** in _geonetworking_ fails, but I think it might just be related to Victor's problem. It may also cause the BasicSocketTest failure.

To put a long story short: In my particular case (BeaconTest), creating a GeonetStation from BtpSocket.on (...) takes several seconds, which causes the time-restricted test to fail. I went through the code, tried some alternative initialization constructions in GeonetStation (like initializing 'scheduler' in the constructor), but  could not find any reason why it should take so long... It just seems to take several seconds to _even_ _reach_ the constructor GeonetStation, so either loading the class or doing its static initialization takes several seconds and causes the enclosing test to fail, at least with a 3s expiration time ...

Here's an excerpt from the log of 'mvn test -Dtest=BeaconTest', with the System.out output, with an 8-seconds expiration time (in which case the test succeeds), with an indication of where time is 'severely lost'. It looks like increasing the test expiration time could solve the problem, but this does not explain why creating a GeonetStation should take several seconds (my estimate on the ALIX is around 4 seconds...). The [1] and [2] in the output refer to the two distinct GeonetStation constructors ([2] is called from [1]).

Hopefully you can shed some light on this... Thanks, Jan.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.gcdc.geonetworking.BeaconTest
Entering BeaconTest
Creating DuplicatorLinkLayer
Creating two users for DuplicatorLinkLayer
Creating new StationConfig
Creating empty address
Creating PositionProvider
Creating BtpSocket
BtpSocket.on: creating GeoNetstation.
**--> COMMENT **THIS TAKES SEVERAL SECONDS!** <--
**Entering (new) GeonetStation[2].
20:04:36.151 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1653072834181778963 and MAC address MacAddress[0]
Exiting (new) GeonetStation[2].
Exiting (new) GeonetStation[1].
BtpSocket.on: starting station thread.
BtpSocket.on: starting beacon service on station.
20:04:36.230 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
receice [request] on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
BtpSocket.on: returning new BtpSocket object for runningStation.
Attempting beacon reception
receice [request] on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.
20:04:36.294 [pool-1-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.
Asserting beacon correctness
Exiting BeaconTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.139 sec
20:04:37.695 [pool-1-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.
20:04:37.745 [pool-1-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.
20:04:37.789 [pool-1-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.
20:04:37.854 [pool-1-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@69d5af30.
addToQueue on net.gcdc.geonetworking.DuplicatorLinkLayer$1@47cce62c.

Results :

Tests run: 1, Failures: 0, Errors: 0, Skip

**Comment by alexvoronov** [comment]
I'll try to add more logging everywhere to find what exactly requires so much time. There are several schedulers and some networking code (get localhost address) that are the first suspects. The rest of the code is plain and straightforward, with no complicated static initializers.

**Comment by victordolk** [comment]
After running 

export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 (without this it gives the error: unmappable character for encoding ASCII) 
mvn clean install

I get the following:

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Parent for GeoNetworking
[INFO] GeoNetworking
[INFO] Datatypes for ASN.1
[INFO] CAM and DENM message spec
[INFO] UPER encoder for ASN.1
[INFO] Upper Tester for GeoNetworking
[INFO] Vehicle Adapter (Simulink-UDP)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Parent for GeoNetworking 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ parent ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ parent ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/root/geonetworking/target/jacoco.exec,excludes=net/gcdc/uppertester/**/*.class:net/gcdc/plugtestcms4/**/*.class
[INFO]
[INFO] --- maven-install-plugin:2.3:install (default-install) @ parent ---
[INFO] Installing /root/geonetworking/pom.xml to /root/.m2/repository/net/gcdc/parent/0.0.1-SNAPSHOT/parent-0.0.1-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building GeoNetworking 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ geonetworking ---
[INFO] Deleting file set: /root/geonetworking/geonetworking/target (included: [**], excluded: [])
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ geonetworking ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/root/geonetworking/geonetworking/target/jacoco.exec,excludes=net/gcdc/uppertester/**/*.class:net/gcdc/plugtestcms4/**/*.class
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ geonetworking ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/geonetworking/geonetworking/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ geonetworking ---
[INFO] Compiling 41 source files to /root/geonetworking/geonetworking/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ geonetworking ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ geonetworking ---
[INFO] Compiling 18 source files to /root/geonetworking/geonetworking/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ geonetworking ---
[INFO] Surefire report directory: /root/geonetworking/geonetworking/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Running net.gcdc.geonetworking.BasicSocketTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.294 sec <<< FAILURE!
Running net.gcdc.geonetworking.DestinationTest
17:36:03.537 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1653010398149390333 and MAC address MacAddress[0]
17:36:03.680 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
17:36:03.703 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1653010334507297703 and MAC address MacAddress[0]
17:36:03.713 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1219)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:338)
        at net.gcdc.geonetworking.DuplicatorLinkLayer$QueuingLinkLayer.addToQueue(DuplicatorLinkLayer.java:28)
        at net.gcdc.geonetworking.DuplicatorLinkLayer.sendToAll(DuplicatorLinkLayer.java:34)
        at net.gcdc.geonetworking.DuplicatorLinkLayer$1.send(DuplicatorLinkLayer.java:40)
        at net.gcdc.geonetworking.GeonetStation.sendToLowerLayer(GeonetStation.java:531)
        at net.gcdc.geonetworking.GeonetStation.send(GeonetStation.java:148)
        at net.gcdc.geonetworking.BtpSocket.send(BtpSocket.java:25)
        at net.gcdc.geonetworking.BasicSocketTest.test(BasicSocketTest.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.lang.Thread.run(Thread.java:745)
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.926 sec
Running net.gcdc.geonetworking.UdpDuplicatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.136 sec
Running net.gcdc.geonetworking.AddressTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.114 sec
Running net.gcdc.geonetworking.AreaAndPositionTest
17:36:07.123 [pool-3-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.463 sec
Running net.gcdc.geonetworking.CommonHeaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.22 sec
Running net.gcdc.geonetworking.DuplicateLinkLayerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec
Running net.gcdc.geonetworking.GeonetDataTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.247 sec
Running net.gcdc.geonetworking.BasicGeobroadcastTest
17:36:07.935 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1652845755033156842 and MAC address MacAddress[0]
17:36:07.944 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
17:36:07.952 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1653067552433842933 and MAC address MacAddress[0]
17:36:07.962 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
17:36:07.969 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1652981115671715548 and MAC address MacAddress[0]
17:36:07.977 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
17:36:07.986 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1652862006805172341 and MAC address MacAddress[0]
17:36:07.993 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.189 sec
Running net.gcdc.geonetworking.BasicHeaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.196 sec
Running net.gcdc.geonetworking.BeaconTest
17:36:08.330 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Initialized station with GN address 1652899018095484204 and MAC address MacAddress[0]
17:36:08.344 [Time-limited test] INFO  net.gcdc.geonetworking.GeonetStation - Starting BEACON service
17:36:08.386 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 sec
Running net.gcdc.geonetworking.LongPositionVectorTest
17:36:08.430 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.475 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.520 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.571 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.616 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.662 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.706 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.729 [pool-9-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.752 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.796 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.815 [pool-7-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.838 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.854 [pool-5-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.882 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.929 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:08.976 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.588 sec
Running net.gcdc.geonetworking.TrafficClassTest
17:36:09.027 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec
Running net.gcdc.geonetworking.MacAddressTest
17:36:09.073 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 sec
17:36:09.117 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:09.160 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:09.208 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:09.243 [pool-9-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon
17:36:09.259 [pool-13-thread-1] INFO  net.gcdc.geonetworking.GeonetStation - Sending beacon

Results :

Tests in error:
  test(net.gcdc.geonetworking.BasicSocketTest): test timed out after 3000 milliseconds

Tests run: 23, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent for GeoNetworking .......................... SUCCESS [6.980s]
[INFO] GeoNetworking ..................................... FAILURE [36.593s]
[INFO] Datatypes for ASN.1 ............................... SKIPPED
[INFO] CAM and DENM message spec ......................... SKIPPED
[INFO] UPER encoder for ASN.1 ............................ SKIPPED
[INFO] Upper Tester for GeoNetworking .................... SKIPPED
[INFO] Vehicle Adapter (Simulink-UDP) .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.850s
[INFO] Finished at: Mon May 08 17:36:09 GMT+00:00 2017
[INFO] Final Memory: 17M/120M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project geonetworking: There are test failures.
[ERROR]
[ERROR] Please refer to /root/geonetworking/geonetworking/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :geonetworking


and report file states the following
-------------------------------------------------------------------------------
Test set: net.gcdc.geonetworking.BasicSocketTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.295 sec <<< FA
test(net.gcdc.geonetworking.BasicSocketTest)  Time elapsed: 3.13 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 3000 millise
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.exists(File.java:813)
        at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1080)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:358)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at ch.qos.logback.classic.util.DefaultNestedComponentRules.addDefaultNes
        at ch.qos.logback.classic.joran.JoranConfigurator.addDefaultNestedCompon
        at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(Generi
        at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(Jora
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConf        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConf
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConf
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConf
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(Co
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInit
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
        at net.gcdc.geonetworking.GeonetStation.<clinit>(GeonetStation.java:40)
        at net.gcdc.geonetworking.BtpSocket.on(BtpSocket.java:14)
        at net.gcdc.geonetworking.BasicSocketTest.test(BasicSocketTest.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.lang.Thread.run(Thread.java:745)

**Comment by victordolk** [comment]
I changed the timeout in BasicSocketTest.java. So the only problem seems to be the time it takes

**Comment by alexvoronov** [comment]
I don't have those huge delays on my platform, and I don't have access to the APU. So I suggest just increase the timeout and close the issue. Which timeouts and how much did you increase to get it working?

**Comment by jandejongh** [comment]
Hi Alex, so far a timeout of 8s works fine for me on the APU. I've been looking into it, and discovered that on the APU, the static 'logger' fields cause several seconds of delay. But if I remove them, the problem pops up elsewhere... I'm afraid it's just a weird APU+openjdk thing or something.

For me, it applies to BeaconTest and BasicSocketTest.

Thanks, Jan

**Comment by alexvoronov** [comment]
Thanks Jan! I have pushed 39ccda512e8da85647f4c00c796553dbd346393b that increases the timeouts. I close the issue for now, feel free to reopen it if it is still broken.  /Alex

**Comment by jandejongh** [comment]
Thanks Alex! BR, Jan
