### ISSUE TITLE
Critical race in GN beacon generation?

### ISSUE THREAD

**Issue by jandejongh** [alexvoronov/geonetworking#16]
Hi Alex,

From our experiences here in Spain, we think there is a 'critical race' in the GN beacon generation. In many cases, we found that stations send beacons at increasing rates, even in the presence of (e.g.) CAM transmissions. Actually, the more CAMs are sent (25 Hz :-)), the worse the problem gets.

I guess the following line of code in GeonetStation.java is somewhat suspicious:

@Override public void skipNextBeacon() { beaconFuture.cancel(false); scheduleNextBeacon(); }

because the beaconFuture.cancel (false) can actually fail, in which case more and more chains of 'beaconFuture' instances will remain dangling; each generating new beacons at (roughly) 1/3 Hz rate forever.

What do you think? Should we check/wait until we are sure that the beaconFuture is actually cancelled? (It seems to return a value indicating whether the cancellation succeeded or not).

Thanks, and best wishes from Spain,
Jan

**Comment by alexvoronov** [comment]
Hmm... I see how this can happen if cancelling fails. 
I have a few guesses how to avoid it, I will implement something, but I think I won't be able to test it: I don't know how to force cancelling a Future to fail. So I will need some help with testing later.

**Comment by jandejongh** [comment]
Alex, thanks, no problem, I can test this quite well, but it'll take a few days to restore my setup (had to break it down for the testing @IDIADA).

**Comment by alexvoronov** [comment]
Jan @jandejongh, I have pushed ea3142b88437fa2d7b055f2ed76a49a8beea254d, could you please try if it solves the racing condition?

It is not a "perfect" in the sense that there might be potentially a double-interval between beacons if a CAM was sent right after one beacon. Think beacon at 10.000, then next should be at 11.000, but a CAM at 10.001 makes beacon at 11.000 obsolete, and the next beacon that is sent is at 12.000. So there will be a pause between 10.001 and 12.000 with no beacons. I think this is an acceptable behavior anyway.

**Comment by Heuvendw** [comment]
There was a little issue with the beacon resetting (every message would increase beacon time):
`@Override public void skipNextBeacon() {
            nextBeaconTime = nextBeaconTime.plusMillis(randomDelayMs());
        }`
should be changed to
`@Override public void skipNextBeacon() {
            nextBeaconTime = timeInstantNow().plusMillis(randomDelayMs());
        }`

**Comment by alexvoronov** [comment]
Yes, of course, you're right. I'll change it right away.

**Comment by alexvoronov** [comment]
I missed the pull request with the change. I guess beaconing worked well then? If not, reopen this issue.
