### ISSUE TITLE
GpsdClient semi-open connections?

### ISSUE THREAD

**Issue by Heuvendw** [alexvoronov/geonetworking#18]
Hi Alex,
I'm currently having some issues with the gpsdclient losing its active connection.
It appears as if the connection is semi-closed as it does no longer receive data from gpsd after a while (or on certain runs) but the sockets are 'connected'. In this case xgps or cgps can be run, which show the received data, but the application no longer receives it.

Did anyone else encounter the same issue?

**Comment by Heuvendw** [comment]
I wrote a 'small' alternative implementation which no longer suffers this issue for me, using a telnet client.[GpsdClient.java.txt](https://github.com/alexvoronov/geonetworking/files/255359/GpsdClient.java.txt)

This implementation does suffer from incomplete message blocks which cause the TPV message to be rejected (only half messages are received?), however this implementation catches these exceptions and recovers from these issues (including a disconnected and reconnected GPS receiver).

This code may replace the existing code but the pom.xml file needs an additional dependency:
`<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.3</version>
		</dependency>`

PS. could it be that the original implementation suddenly received an incomplete message and closed itself in the background? (The threadpool executor appears to 'hide' exceptions)

**Comment by alexvoronov** [comment]
I'm not sure what's happening there, I'd have to look into it in more detail. Extra dependencies is not a problem, just send a pull request when you think it is working good. We can also look into it during GCDC preparation already next week.

**Comment by alexvoronov** [comment]
Ah, I missed the pull request :)
Now it is merged, and I close this issue.
