### ISSUE TITLE
Lib does not run on Android

### ISSUE THREAD

**Issue by sh-hilden** [alexvoronov/geonetworking#47]
Hi, the Lib does not run under Android. 
I found the problem on it. It is the Class Asn1ContainerFieldSorter on the constructor in Line 327. There the method “type.getDeclaredFields()” is called. On the normal Java VM you get the fields in Declaration order. But on Android the fields are sorted randomized.

I add a static function to every class in the datatype declaration which get a list of the fields in right order. Now it works for me.

**Comment by alexvoronov** [comment]
Thanks for reporting this!

According to https://stackoverflow.com/a/5004929 and https://stackoverflow.com/a/31117045, after the files are compiled there is no way to get the source order. JDK 6 and later use the source order, and Asn1ContainerFieldSorter relies on that. Apparently Android uses its own order, which is unfortunate.

There might be a number of possible workarounds, but any I can think of would complicate the code. Yours is a very good workaround. Another one is to add an annotation to each field with a correct index. But the best solution would be to convince Android developers to store fields in the source order.


I'll close the issue for now, let me know if you think it should be reopened.
