### ISSUE TITLE
Failing Test - DestinationTest#test4

### ISSUE THREAD

**Issue by snodnipper** [alexvoronov/geonetworking#49]
Similar to https://github.com/alexvoronov/geonetworking/issues/48 I am getting a similar issue in the DestinationTest.

Will update after a bit of debugging.

![screen shot 2018-08-31 at 17 26 00](https://user-images.githubusercontent.com/576719/44924354-f4b8d200-ad42-11e8-8e5d-5f90dc0f9276.png)

**Comment by snodnipper** [comment]
Ok, so it would appear to be caused by Beacon not overriding #equals.

![screen shot 2018-08-31 at 17 31 30](https://user-images.githubusercontent.com/576719/44924628-cdaed000-ad43-11e8-8260-e4274d058115.png)

```java
    @Test
    public void test4() {
        EqualsVerifier.forClass(Destination.Beacon.class).verify();
    }
```

```java
    @Test
    public void test4() {
        EqualsVerifier.forClass(Destination.Beacon.class)
            .suppress(Warning.INHERITED_DIRECTLY_FROM_OBJECT)
            .verify();
    }
```

**Comment by alexvoronov** [comment]
Am I right that this code fixes the problem? I don't have Android compiler, so I can't check. If it works, could you open a pull request?

**Comment by snodnipper** [comment]
Resolved in https://github.com/alexvoronov/geonetworking/pull/51

👍
