### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by cuita85202** [alexvoronov/geonetworking#52]
Hi Alex,
 
First of all, I want to thank you for this great work.
I have a build problem. 
<img width="1428" alt="capture d ecran 2018-10-21 a 21 54 47" src="https://user-images.githubusercontent.com/10993750/47271701-03ba4480-d57c-11e8-965c-a108b6028b6c.png">
<img width="1429" alt="capture d ecran 2018-10-21 a 21 54 57" src="https://user-images.githubusercontent.com/10993750/47271706-0cab1600-d57c-11e8-8a5c-91c1bc1e60fb.png">

Thanks,

Cuita

**Comment by alexvoronov** [comment]
Hi Cuita! I never had this error, and from your screenshots I can't even figure out what the error is. Could you pinpoint the error?

**Comment by cuita85202** [comment]
Hi, 

I think it was my fault trying to build the program with "mvn clean install" and directly i had this error message. But I had to run "udp2eth" before? 
Sorry maybe i ask basics question, but I have just started using Maven so I don't know how to build the program or even if I have to?
I did import the program in my Eclipse programme. So I can start using it directly? 

Sorry for this basics questions 
Cuita

**Comment by alexvoronov** [comment]
You are right that you have to build geonetworking first. The error you get is when you are building with Maven. The error message you pasted recommends looking in the log file, and also re-running with -e and -X switches. See if that gives hints as to what is going wrong. I also see it says "forked VM terminated" - I found some solutions on StackOverflow: https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi , see if any of them work. It seems like it is from maven-surefire-plugin, you can try disabling the tests with "-DskipTests=true" (see maven and maven-surefire-plugin docs for details on how to disable the tests).

Hope this helps, and let me know how it goes!

**Comment by severinson** [comment]
I had the same issue. Bumping the version of jacoco-maven-plugin resolved the issue in my case. I've submitted a pull request.
https://github.com/alexvoronov/geonetworking/pull/53

**Comment by cuita85202** [comment]
> You are right that you have to build geonetworking first. The error you get is when you are building with Maven. The error message you pasted recommends looking in the log file, and also re-running with -e and -X switches. See if that gives hints as to what is going wrong. I also see it says "forked VM terminated" - I found some solutions on StackOverflow: https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi , see if any of them work. It seems like it is from maven-surefire-plugin, you can try disabling the tests with "-DskipTests=true" (see maven and maven-surefire-plugin docs for details on how to disable the tests).
> 
> Hope this helps, and let me know how it goes!

Thank you for your quick reply

**Comment by cuita85202** [comment]
> I had the same issue. Bumping the version of jacoco-maven-plugin resolved the issue in my case. I've submitted a pull request.
> #53

That works Thanks a lot

**Comment by alexvoronov** [comment]
I'm glad your problem is solved! Thanks @severinson for the solution!
