### ISSUE TITLE
CAM Decoding

### ISSUE THREAD

**Issue by cuita85202** [alexvoronov/geonetworking#55]
Hey,

I have a problem with CAM message decoding,
when I use the sample uper of a CAM message (taken from the website: https://github.com/bastibl/its-g5-cam) : 01020000000000010006b49d214d693a41400200200030d400000000000000000002840ba9800fffc0
I got the right answer : 
<img width="653" alt="capture d ecran 2019-01-08 a 17 58 45" src="https://user-images.githubusercontent.com/10993750/50846315-208e3900-136f-11e9-853a-9bc3662e8e75.png">
but when I use a uper taken from a real CAM message
<img width="978" alt="capture d ecran 2019-01-08 a 17 40 22" src="https://user-images.githubusercontent.com/10993750/50846587-d194d380-136f-11e9-98a9-acc49918690d.png">
:0102000f6954fb00405a75197750084bcdffffffe00031b51e72000fc0007ebfe7ea8003a9800fffc0009fffc00000
I get this error 
<img width="700" alt="capture d ecran 2019-01-08 a 18 06 21" src="https://user-images.githubusercontent.com/10993750/50846735-259fb800-1370-11e9-8d7d-93ea6302b29b.png">
I know that there has no problem with the code but I if I want to be able to decode these messages I may have to get some changes in UperEncoder. Can you help with that please? and tell me where is the probleme coming from? 

Thank you
Cuita

**Comment by alexvoronov** [comment]
Hi Cuita,

The best way to test the messages is at OSS Playground: http://asn1-playground.oss.com They have implemented CAM v1.3.2. It seems like this message has something wrong.

In any case, there is a problem somewhere in my decoder too, it should never throw IndexOutOfBoundsException for malformed input, it should throw IllegalArgumentException instead, with an explanation about which part exactly is wrong.

I don't have time to look into it in details right now. If you come up with a solution, please do open a pull request, and I will happily merge it!

Alex

**Comment by cuita85202** [comment]
Thank you for your response, 
I already did (test it with OSS Playground) and it is decoded normally. 
And yes I'm trying to figure out where is the problem coming from. 
If you have some time that will be good if you can put some comments on the code in class UperEncoder it will help me a lot to figure out.

thank you 
Cuita

**Comment by alexvoronov** [comment]
I feel your frustration, it is very convoluted code. There are lots of operations on bits, which are difficult to keep track of. It was written in a hurry, without long-term maintenance in mind. But it is free. The best documentation for the code is ASN.1 UPER standard itself, I tried to write code that would be as close to the document in the names and structures, while at the same time taking as many shortcuts as possible to finish a minimal working version faster.

By the way, I tried again your message (`0102000f6954fb00405a75197750084bcdffffffe00031b51e72000fc0007ebfe7ea8003a9800fffc0009fffc00000`) in the OSS Playground and got the following error:
```
End of input reached before message was fully decoded; check field 'pathHistory' of field 'basicVehicleContainerLowFrequency' of field 'lowFrequencyContainer' of field 'camParameters' of field 'cam' of PDU #1.
```

**Comment by cuita85202** [comment]
Yes I understand, but still it is a huge job that you have accomplished. 
Thank you for sharing it with us.

**Comment by alexvoronov** [comment]
I looked at the code again.

Exception is thrown from [L278](https://github.com/alexvoronov/geonetworking/blob/a4c10a72645bd9e121152402c1142cd17dfc06e0/asn1-uper/src/main/java/net/gcdc/asn1/uper/UperEncoder.java#L278). Right before it there is a log message on [L271](https://github.com/alexvoronov/geonetworking/blob/a4c10a72645bd9e121152402c1142cd17dfc06e0/asn1-uper/src/main/java/net/gcdc/asn1/uper/UperEncoder.java#L271), but no condition to raise an exception if there are less bits available in the `bitqueue` than would be required to decode the value.

Could you please turn on logging and check if this log message indeed says that required bits are more than are available?

**Comment by cuita85202** [comment]
Hey, 

Sorry for this delay, I didn't have my computer yesterday.
Indeed I got this: 
<img width="751" alt="capture d ecran 2019-01-10 a 16 56 20" src="https://user-images.githubusercontent.com/10993750/50980374-d3d66980-14f8-11e9-8f16-47c7f7ab74e3.png">

**Comment by cuita85202** [comment]
Aw sorry, your question was if equired bits are more than are available. but here is the opposit. 
and it the same case even for the successfully decoded message
<img width="724" alt="capture d ecran 2019-01-10 a 17 03 40" src="https://user-images.githubusercontent.com/10993750/50980882-0339a600-14fa-11e9-9dc6-ff6ebbc9aa7a.png">

**Comment by alexvoronov** [comment]
Hi, I have pushed a commit, it should now throw IllegalArgumentException for incomplete messages.

**Comment by alexvoronov** [comment]
I believe `IndexOutOfBoundException` is gone, and I'm closing this issue. If the exception shows up again, feel free to reopen the issue.

**Comment by cuita85202** [comment]
That worked, thank you so much for your help. 

cuita
