### ISSUE TITLE
int extension are not supported yet

### ISSUE THREAD

**Issue by littleloulou** [alexvoronov/geonetworking#58]
This libary not supprot bit string with extension  such as asna file :?

	LaneAttributes-Vehicle ::= BIT STRING { 
		-- With bits as defined:
		isVehicleRevocableLane (0),
		-- this lane may be activated or not based
		-- on the current SPAT message contents
		-- if not asserted, the lane is ALWAYS present
		isVehicleFlyOverLane (1),
		-- path of lane is not at grade
		hovLaneUseOnly (2),
		restrictedToBusUse (3),
		restrictedToTaxiUse (4),
		restrictedFromPublicUse (5),
		hasIRbeaconCoverage (6),
		permissionOnRequest (7) -- e.g. to inform about a lane for e-cars
		} (SIZE (8,...))

**Comment by alexvoronov** [comment]
You are right, it is not supported. I will look into implementing it when I will have time.

**Comment by alexvoronov** [comment]
Actually, you can encode your example as a sequence of booleans:

```java
    @SizeRange(minValue = 8, maxValue = 8, hasExtensionMarker = true)
    public static class LaneAttributes extends Asn1SequenceOf<Boolean> {
        public LaneAttributes(Collection<Boolean> coll) { super(coll); }
    }
```

See test case in a67b87c34bd075084228ca5873c7ba69a191a9ce. Let me know if this works for you.

**Comment by littleloulou** [comment]
Thank you !  I ran your code without problems.However, when I went to decode the c++ encoded asn1 data, an error occurred: java.lang.UnsupportedOperationException: int extension are not supported yet,The asn1 file used is the same,as my fisrt asked file.

**Comment by alexvoronov** [comment]
Could you open a new issue and attach a minimal example of the code? I took a quick look at the code: https://github.com/alexvoronov/geonetworking/blob/90e98ce73022dc71b8f8cec544204165afd02f0e/asn1-uper/src/main/java/net/gcdc/asn1/uper/UperEncoder.java#L259-L265 There is no decoding implemented for cases when extensions are active (values outside of the original range).

**Comment by littleloulou** [comment]
> Could you open a new issue and attach a minimal example of the code? I took a quick look at the code:
> 
> https://github.com/alexvoronov/geonetworking/blob/90e98ce73022dc71b8f8cec544204165afd02f0e/asn1-uper/src/main/java/net/gcdc/asn1/uper/UperEncoder.java#L259-L265
> 
> There is no decoding implemented for cases when extensions are active (values outside of the original range).

ok,I found this code also ,but don't know how to implement it.
